### ISSUE TITLE
你这个是拉哪些文件进去啊？

### ISSUE THREAD

**Issue by AllLuckly** [lerosua/DWZShareKit#8]
我拉了你的core 文件   和extend 文件。。我还没干嘛呢。。。就报 14 个错、、、、求解

**Comment by AllLuckly** [comment]
Unknown type name 'UIImage'

**Comment by AllLuckly** [comment]
Property 'size' not found on object of type '__strong id'
  还有好多的错。。。

**Comment by lerosua** [comment]
使用pod导入吧，光拉文件就要解决引入framework的问题，应该是UIKit没导入，这类问题得自行解决。
